CREATE TABLE users (
    id TEXT PRIMARY KEY UNIQUE NOT NULL,
    type VARCHAR,
    gender CHAR(1),
    name_title VARCHAR,
    name_first VARCHAR,
    name_last VARCHAR,
    location_region VARCHAR,
    location_street VARCHAR,
    location_city VARCHAR,
    location_state VARCHAR,
    location_postcode INT,
    location_coordinates_latitude DOUBLE,
    location_coordinates_longitude DOUBLE,
    location_timezone_offset VARCHAR,
    location_timezone_description VARCHAR,
    email VARCHAR,
    birthday VARCHAR,
    registered VARCHAR,
    telephone_numbers VARCHAR,
    mobile_numbers VARCHAR,
    picture_large VARCHAR,
    picture_medium VARCHAR,
    picture_thumbnail VARCHAR,
    nationality CHAR (2)
);